// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxfs6C6_mLlW9UHDj5ScL5_nYeW6lva8',
    appId: '1:195160711893:web:152976fa84c2f350fff85c',
    messagingSenderId: '195160711893',
    projectId: 'chattini-e770d',
    authDomain: 'chattini-e770d.firebaseapp.com',
    storageBucket: 'chattini-e770d.firebasestorage.app',
    measurementId: 'G-SFN1M13NP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVKYD2r87y-8u3yLW4HDD6oBY05fG4Aw',
    appId: '1:195160711893:android:b28b33f4dde1c266fff85c',
    messagingSenderId: '195160711893',
    projectId: 'chattini-e770d',
    storageBucket: 'chattini-e770d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADycXQutoL3J9W5zB2YO3E8C2O4DqChCQ',
    appId: '1:195160711893:ios:1729c0aae9182852fff85c',
    messagingSenderId: '195160711893',
    projectId: 'chattini-e770d',
    storageBucket: 'chattini-e770d.firebasestorage.app',
    androidClientId: '195160711893-oo8n3lvsvg57993mvbh3m58tkb076tpk.apps.googleusercontent.com',
    iosClientId: '195160711893-o006938e5mt4o6262d01rphs8k871s66.apps.googleusercontent.com',
    iosBundleId: 'com.example.instachatV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADycXQutoL3J9W5zB2YO3E8C2O4DqChCQ',
    appId: '1:195160711893:ios:1729c0aae9182852fff85c',
    messagingSenderId: '195160711893',
    projectId: 'chattini-e770d',
    storageBucket: 'chattini-e770d.firebasestorage.app',
    androidClientId: '195160711893-oo8n3lvsvg57993mvbh3m58tkb076tpk.apps.googleusercontent.com',
    iosClientId: '195160711893-o006938e5mt4o6262d01rphs8k871s66.apps.googleusercontent.com',
    iosBundleId: 'com.example.instachatV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxfs6C6_mLlW9UHDj5ScL5_nYeW6lva8',
    appId: '1:195160711893:web:d53c6880070286a0fff85c',
    messagingSenderId: '195160711893',
    projectId: 'chattini-e770d',
    authDomain: 'chattini-e770d.firebaseapp.com',
    storageBucket: 'chattini-e770d.firebasestorage.app',
    measurementId: 'G-0K45PQN9V3',
  );

}